### ISSUE TITLE
Production KeyRing

### ISSUE THREAD

**Issue by vokimon** [Som-Energia/intercoop#4]
Example implementation of the KeyRing interface skips any concern on how to obtain the Keys. We should consider providing a production ready implementation.

Options:

- **Directory based:** Like example PeerInfo, a directory containing keys with filenames related to the issuing peer.
- **Files + configuration based:** You provide a configuration with the paths for every key
- **PeerInfo based:** We store the public keys in the peerinfo and rely on PeerInfo interface to access them. (PeerInfo implementation will tell whether they are in a DB o any other location)
- **Database based:** We use the underlying platform to get them. (Of course this cannot be that generic)

**Comment by vokimon** [comment]
@bernatixer I opened this discussion. As I was writting it i am quite sure i like the PeerInfo based. This way if you implement PeerInfo as directory based, or database based or whatever you already have it.

The problem them would be how to insert the key into the yaml (in the examples there are different approaches, none used nor working)

**Comment by bernatixer** [comment]
Along with my partner @oriolusler we see the PeerInfo based a good implementation. We could create a new function on `crypto.py` so it could read the public key stored in the peerinfo. And then, maybe get rid of the KeyRingMock used in production?

**Comment by vokimon** [comment]
I'm on it.

There was no clear example on how to store public keys. I propose yaml `|` construct and pem format:

```yaml
publickey: |
  -----BEGIN RSA PUBLIC KEY-----
  MIIBCgKCAQEA2GM+iJj2rQ18Z8boycjKn3Nc89nIFy2EjWU2IpRYSLs7q+dTtOr+
  H39Pl14gtnPqPcyhURwF2QQg7oRy06nhCK736AZwhh7zVqvkIhzUQNvKBv21TQ0x
  6rzVBmtyI1Ounn156Rk36Hdmk0FmDFQk9sL5oYvcuVCpRI0JIo6B9TOEiuCRAsxp
  fjU4Mx0hwSu9lQjxhqgx3KYkdENvGhZCp0nV0IzYqdQEk4q8prJMm46ny5jRZn1I
  JowsQtBozevO+024dFZDQVQhwUlfr47RN0baclgTB3ANxwAnm4j68fywPBGpyW7u
  GQEnpjwdEAA9w/ibgoscc70f/6CCEIgA1QIDAQAB
  -----END RSA PUBLIC KEY-----
```

Regarding the interface i propose:

```python
peerinfo = PeerInfo('peer/info/folder')
keyring = KeyRing(peerinfo)
key = keyring.get("apeer")
crypto.isAuthentic(key, text, signature)
```

This way we can eventually provide a different peerinfo backend than the directory based.

**Comment by vokimon** [comment]
Today commits up to e2c63bbdec1120a2d7813747dc9d05a7495644e5 should fix that.

I left this issue open in order to discuss the proposed solution.
